import './about.css';

function About() {
    return (
        <main className="app-about">
            <h1>About the author</h1>
            <article>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec ullamcorper sem, a elementum ante. Aliquam leo velit, ullamcorper sit amet aliquet quis, pretium eget leo. Nulla non pulvinar nunc. Donec hendrerit iaculis velit volutpat imperdiet. Mauris vitae est a elit molestie imperdiet nec sed libero. Curabitur placerat blandit risus ut accumsan. Duis vulputate est a orci dignissim, gravida mattis nisi viverra. Vestibulum interdum enim et tellus aliquet mollis. Nullam fringilla congue lacus. Vestibulum ullamcorper dolor lectus, sit amet dictum ipsum vehicula quis. Vivamus sapien magna, tempor quis mi a, viverra finibus neque. Curabitur sed enim id nunc egestas congue nec quis enim. Fusce interdum arcu vitae dolor mollis, et porttitor ligula cursus. In faucibus iaculis enim, sit amet cursus tellus. Quisque cursus ipsum vel enim lobortis gravida. Vestibulum pharetra ac diam at congue.
                Fusce ultrices ultrices risus, id porttitor mauris semper vitae. Quisque quis libero ac arcu tristique porta. Duis finibus, mi ut convallis posuere, metus arcu vulputate elit, a tristique elit tellus et lectus. Aenean id ullamcorper tellus. Duis imperdiet augue orci, sit amet scelerisque mauris dignissim sed. Praesent non ligula eget purus dapibus finibus. Sed viverra porttitor scelerisque. Phasellus sed felis eget neque posuere cursus a sagittis turpis. Integer ut magna ante. Etiam in bibendum mauris. Aenean non augue hendrerit, semper felis ac, ultrices nulla. Vestibulum ut nisl libero. Vivamus id metus non neque imperdiet sollicitudin eget non mauris. Morbi auctor ac quam et feugiat.
                Phasellus vitae eros eu lacus scelerisque mollis. Duis felis justo, condimentum mattis tellus eget, tincidunt elementum tortor. Phasellus tempor libero vitae nulla vulputate, nec accumsan metus vehicula. Morbi commodo egestas turpis, vel congue ipsum vehicula a. Mauris accumsan, dui in vulputate eleifend, arcu ante venenatis ex, ac pretium ligula erat sit amet quam. Phasellus mauris felis, faucibus a metus eget, viverra porttitor libero. Vestibulum aliquet tortor vel orci tincidunt feugiat.
                Donec eu eleifend est. Donec mattis, lectus non egestas fringilla, libero purus congue tellus, ut luctus est metus eget mi. In hac habitasse platea dictumst. Maecenas ac velit sed eros lacinia fermentum gravida at lorem. Praesent eu pellentesque nisi. Aenean sed neque non odio vulputate lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque non justo ultrices, vestibulum enim non, rhoncus nulla.
                Morbi imperdiet est id sagittis consequat. Duis convallis congue orci, quis laoreet sem aliquet et. Donec id malesuada urna. Vestibulum porttitor, augue vulputate varius sodales, sapien ligula luctus arcu, non dapibus tellus odio congue purus. Aliquam auctor suscipit dui, ac posuere dolor. Vivamus a turpis mauris. Integer lorem sem, pellentesque ac consectetur rhoncus, congue sit amet ipsum. In hac habitasse platea dictumst. Suspendisse suscipit id orci sed maximus. In fringilla, velit rhoncus pharetra aliquet, urna neque commodo ex, sit amet bibendum felis libero non dolor. Morbi quis scelerisque tellus. Vestibulum ullamcorper iaculis libero quis mollis. Vivamus vulputate commodo blandit. Nullam ut magna eu lectus interdum consectetur. Duis sed euismod enim, eget porta enim.
            </article>
        </main>
    );
}

export default About;